site_name: Computación Afectiva


theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.top
    - navigation.sections
    
  
    
nav:
  - Home: index.md
  - Bases de la computacion Afectiva: 
    - Computacion_afectiva/index.md
    - Computacion Cognitiva: Computacion_afectiva/Computacion cognitiva.md
    - Computacion Cooperativa: Computacion_afectiva/Computacion cooperativa.md
  - Teorias de las emociones:
    - Teoria de las emociones/index.md
    - Marcadores emocionales: Teoria de las emociones/Marcadores emocionales.md
    - Teoria ekman: Teoria de las emociones/Teoria de Ekman.md
    - Emociones primarias y secundarias: Teoria de las emociones/emociones primarias y secundarias.md

  - Monitoraje Passivo: 
    - Monitoraje Pasivo/index.md
    - Ritmo cardíaco:   Monitoraje Pasivo/ritmo cardiaco.md
    - Presión sanguínea:   Monitoraje Pasivo/Presion sanguinea.md
    - Electrocardiograma:   Monitoraje Pasivo/electrocardiograma.md
    - Variación rítmo Cardiaco:   Monitoraje Pasivo/variacion ritmo cardiaco.md
    - Electromiografía:   Monitoraje Pasivo/electromiografia.md
    - Electroencefalograma:  Monitoraje Pasivo/electroencefalograma.md
    - EDA:  Monitoraje Pasivo/EDA.md
  - Monitoraje Activo: 
    - Monitoraje Activo/index.md
    - Patrones de Monitoraje: Monitoraje Activo/Patrones de monitoraje activo.md
  - Patrones de diseño emocionales: 
    - Patrones de diseño emocional/index.md
    - Comunicacion basada en iconos: Patrones de diseño emocional/Comunicacion basada en iconos.md
    - Dificultad adaptativa: Patrones de diseño emocional/Dificultad adaptativa.md
    - Contenido adaptativo en base al estado emocional: Patrones de diseño emocional/Contenido adaptativo en base al estado emocional.md
  - Multinterfaces: 
    - Multiinterfaz/index.md
  - Recursos: 
    - Recursos/index.md
  - Ejemplos: 
    - Ejemplos/index.md
  


markdown_extensions:
  - attr_list
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      
