site_name: Computación Afectiva
site_url: ""
use_directory_urls: False

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.top
    - navigation.sections
    
  
    
nav:
  - Home: index.md
  - Bases de la computacion Afectiva: 
    - Computacion_afectiva/index.md
    - Estado del arte: Computacion_afectiva/estado del arte.md
    - Contexto: Computacion_afectiva\contexto.md
    - Computacion Cognitiva: Computacion_afectiva/Computacion cognitiva.md
    - Computacion Cooperativa: Computacion_afectiva/Computacion cooperativa.md
  - Teorias de las emociones:
    - Teoria de las emociones/index.md
    - Marcadores emocionales: Teoria de las emociones/Marcadores emocionales.md
    - Model of affect: Teoria de las emociones\circumplex model of affect.md
    - Teoria ekman: Teoria de las emociones/Teoria de Ekman.md
    - Emociones primarias y secundarias: Teoria de las emociones/emociones primarias y secundarias.md
  - Monitoraje Passivo: 
    - Monitoraje Pasivo/index.md
    - Ritmo cardíaco:   Monitoraje Pasivo/ritmo cardiaco.md
    - Presión sanguínea:   Monitoraje Pasivo/Presion sanguinea.md
    - Electromiografía:   Monitoraje Pasivo/electromiografia.md
    - Electroencefalograma:  Monitoraje Pasivo/electroencefalograma.md
    - EDA:  Monitoraje Pasivo/EDA.md
    - Expressiones Faciales: Monitoraje Pasivo/Expressiones faciales.md
    - Deteccion basada en texto: Monitoraje Pasivo/Deteccion basade en texto.md
  - Monitoraje Activo: 
    - Monitoraje Activo/index.md
    - Perfil de expression emocional: Monitoraje Activo/Perfil de expression emocional.md
  - Multi Interfaz:
    - multiInterfaz/index.md
  - Patrones de diseño emocionales: 
    - Patrones de diseño emocional/index.md
    - Comunicacion basada en iconos: Patrones de diseño emocional/Comunicacion basada en iconos.md
    - Dificultad adaptativa: Patrones de diseño emocional/Dificultad adaptativa_new.md
    - Contenido adaptativo en base al estado emocional: Patrones de diseño emocional/Contenido adaptativo en base al estado emocional.md
    - Expresión de humor: Patrones de diseño emocional/Expresión de humor.md
    - Trigger Warning: Patrones de diseño emocional/Trigger Warning.md
    - Dialogo empático: Patrones de diseño emocional/Dialogo empático.md
    - Hub basado en emociones: Patrones de diseño emocional/Hub basado en emociones.md
  - Bases de datos multimodales:
    - bases de datos multimodales/index.md
    - bases de datos multimodales/emotionML.md
  - Emotive Chat:
    - emoChat/index.md
    - Características de la app: emoChat/appOverview.md
    - Estructura de la aplicación: emoChat/appStructure.md
  - Ética:
    - etica/index.md
  - Recursos: 
    - Recursos/index.md
  - Ejemplos: 
    - Ejemplos/index.md



markdown_extensions:
  - attr_list
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


      
